from sqlmodel import Field, SQLModel


class User(SQLModel, table=True):
    """
    Proxy model for the 'user' table generated by Better Auth.
    We don't inherit from BaseModel because Better Auth uses a standard string ID,
    not a UUID. This model is just so SQLModel relationships can function.
    """

    id: str = Field(primary_key=True)
    name: str
    email: str
    image: str | None = None
