"""add activity_log

Revision ID: ec6c1ab2cf09
Revises: c2d3e4f5a6b7
Create Date: 2026-08-31 14:19:42.788136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec6c1ab2cf09'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activitylog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activitylog_action_type'), 'activitylog', ['action_type'], unique=False)
    op.create_index(op.f('ix_activitylog_actor_id'), 'activitylog', ['actor_id'], unique=False)
    op.create_index(op.f('ix_activitylog_event_id'), 'activitylog', ['event_id'], unique=False)
    op.create_index('ix_activitylog_event_id_created_at', 'activitylog', ['event_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activitylog_id'), 'activitylog', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activitylog_id'), table_name='activitylog')
    op.drop_index('ix_activitylog_event_id_created_at', table_name='activitylog')
    op.drop_index(op.f('ix_activitylog_event_id'), table_name='activitylog')
    op.drop_index(op.f('ix_activitylog_actor_id'), table_name='activitylog')
    op.drop_index(op.f('ix_activitylog_action_type'), table_name='activitylog')
    op.drop_table('activitylog')
    # ### end Alembic commands ###
